spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
  main:
    allow-circular-references: true

kafka:
  topic: first_app
  timeout: 60000

feign:
  enabled: false

data:
  sending:
    method: feign
server:
  port: 8091
