version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181
    volumes:
      - ./zookeeper:/container_folder
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic1:1:1"
    volumes:
      - ./kafka:/container_folder

  postgres:
    image: postgres:13-alpine
    ports:
      - 5431:5431
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data